jobs:
  include:
  - stage: Pre-built Test
    language: node_js
    node_js:
    - node
    cache:
      directories:
      - node_modules
  - stage: Test
    script:
    - echo "Testing"
    - docker build -t $DOCKER_USERNAME/express-boilerplate-test --build-arg "SOURCE_COMMIT=$(git rev-parse HEAD)" -f Dockerfile.test .
    - docker run --rm $DOCKER_USERNAME/express-boilerplate-test
  - stage: Build and Publish
    script:
    - echo "Building"
    - export LAST_COMMIT_SHA="${LAST_COMMIT_SHA:-$(git rev-parse HEAD)}"
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/express-boilerplate --build-arg "SOURCE_COMMIT=$(git rev-parse HEAD)" .
    - docker images
    - echo "Publishing to docker registry"
    - docker tag  $DOCKER_USERNAME/express-boilerplate $DOCKER_USERNAME/express-boilerplate
    - docker push $DOCKER_USERNAME/express-boilerplate
env:
  global:
  - secure: l0o418EPLL/Yvm2lPCmL9vvODPmFGAqwcerW6+ugZK/pxVLYOxNfNaftmDi6JZ1lFsVXK9YYsCY5phjN1cywqWVvobP6PjnL62h9JivA3Lnf1Ud+ggCk05oDEqKI+YYAWr67BXG5o+h/Nysug3265kH3HmuPfBThmqzmu04iyt3ecLpm3ZcOFCZvPh8qkt8H7pHhrvihcwHPCuwrO8I8dMxODsnI6Fv9LH8kEwn7oYSjJ3w2gNpzcu9bekpbA5wpcoF+poJ10Ky2vhOx9j1jm3yxpyxo581XiXfbjUrXkwroqg4gishn8cQ9H+AmBGLXkuk3iwW9kxVIBG3UfMarq/0SC7TtYtOiFbIHdklt4Qa9XFucsMbENHaYqgqZaoKy3Dfx08sibHzaqiT1w6sVLdUFbFNiq0wfXrE9sLciFhBVRPicD3wUX/NlZgmYAiw7omAL/dp+6UGuOg39DAuaqz/gUOZRmkjE5JllEQ5IAc5wFfnaYaP1VnxhpCJBnFkAR/tuRyfK/cmWZiE2u8wMNTfu25MUDn4MLoWw1986ItK+V9HApE3caQDqMcjQw5zKp/o6OKkKBU9MwnOjcY3gDq3ithyvTPYftypi/3c/fy1oAfjb3BA36+jHD/XeO3W+OpOdQrLT4t+0tgXtdW4JblwtuIKeGG2w/IKAWGSOcoc=
  - secure: SrjqUUhYR071nnDy/Ob7lDA8suaq+YYs0M/B+Gudz3+wPAx2D1rnRgfFgpq0LxUz4sNsWlKY9Ex2n6my8tiju6u1ztiRsdGDVOUKYItg0A1P+psroJ8/D4m/+/MVOTVaID4tnFmRHYR4HsyMNAQFEMYCtuzgKgFMzTf4+yC+avZYHDzyTH43MORcq18v7zhKat9vAdhGB7kGE5+95VUNGX/tXF+drqiIF5+z3I73rk1iYcyvUiijx66i86KXrr9cBSK5J8C2b28KTY0B0qgSR6pQ1G3GqUMUIoQBE7rDXeTR5UEntGhBJvj0SEq3i9Jc3SBwx35rk3R1AJxu3V9K3ZwyoKcu04Ni2Qg/osc9JaNkCyeKVzbRUGaL9bGu9Fiq800TEFH9fgjolYln2jArGnw8TcT9dzFg9YKxq/JLq2yHhHujqF3m7LIBulGPlS8djPL5tok5MSWJh5WksfrHxZvgUHb3PyBbGKZ+wlQeDbOChPkoN5DOiI+Vti0e8YyweHmit6WblxdCsotSRVG3q8z2idUnvzX6HkTwtG53ER5sbX0ZaLsiCOn7G+SUKy8xAqbIxoUTEFYNxG56YnwgRCs3qY8aH7WoDGJ4edA0VvtZP0rkNzSoN+uImzQyiIe4vECqxwbWGIbxIHBOXTUB/uI8w38cN7zEF9x4DM/40DI=
