jobs:
  include:
  - stage: Pre-built Test
    language: node_js
    node_js:
    - node
    cache:
      directories:
      - node_modules
  - stage: Test
    script:
    - echo "Building test image and running tests"
    - docker build -t $DOCKER_USERNAME/express-boilerplate-test --build-arg "SOURCE_COMMIT=$(git rev-parse HEAD)" -f Dockerfile.test .
    - docker run --rm $DOCKER_USERNAME/express-boilerplate-test
  - stage: Build and Publish
    script:
    - echo "Building production image"
    - export LAST_COMMIT_SHA="${LAST_COMMIT_SHA:-$(git rev-parse HEAD)}"
    - echo "$DOCKER_PASS" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - docker build -t $DOCKER_USERNAME/express-boilerplate --build-arg "SOURCE_COMMIT=$(git rev-parse HEAD)" .
    - docker images
    - echo "Publishing to docker registry"
    - docker tag  $DOCKER_USERNAME/express-boilerplate $DOCKER_USERNAME/express-boilerplate
    - docker push $DOCKER_USERNAME/express-boilerplate
env:
  global:
  - secure: gqKNlNUUSuDzPGVSSV9+zDn4M+K43orodtjLgY0Tisxl87dF2eNiWcVqtwN8AnQYmFUUb3Yp+P+6HQS9NXksjB4ofwfP4NsFWKLQAlBPeuOvJSb0cdbWu4TFGM2uTZObNBZUZ0PLX+/sEulBQpw2OxVEYw5SzHQx2KGXP/IiuLllXOKmuMSJFG47qM7ZFO/eYvSb3LQZeCnKZVl4JI/1VaB65WwlWbgoHdeMFY/RNdySNVcHxLu7U16sOAQL/+RkZ5ylHQ0Ji1qwRUKgI1xnCsOZ5p/Jzb6yYvDq3zCQWRsxX35SsENJmETUdrND9u7IxoVjezV0JTDnrOI+1ZhRTYVgtvC+nE9A1g3siLIJl16cckBHo1KcU0ceHOu/jnUh07i+z8OYMtpdsDBnU63RixqGnM3Jlu5bwQwdf9dqDqjtKj+mIy1yJ5pv9kNVS64QJihqGjcJxK1SwH5ZH+hiq4tmmBft2TZNfyGnUQTOrArQTOyqQxu8Ho1eUoSp6yTvEPR+ocngiITUjgkIv0yK7NBs33y3iSkWmEihyBEI2vt7fz5v2FNqX8XA9bUVEibLK8bQ8fSH1yMYX4Gim/a+ZR812on1Q2174XTacTVOtck+ptc+VDnlgknqdoKXeN1JZMaV8KbCwN8Ev/u6s8jhjvbiHm48FpOyWW10Ge5zkT8=
  - secure: Ir2uQkTec9QlfnhiZobCVgpudmpdisLDTRq0qemD4xYOYnbixrMmXxB+w3uLrW1Dn74pYjcVlwxNLTA6r/aHPrl28R0ImZn1C9+hLl/4HAraxa1eTzTr+sPxwsdTv+PJcheXPTufAdzWu/6SO59oRAEjmfYloIW1Q8no6iAx/YMtPa6ZCTzrpxhjlQsfqcPpCqzG7VzWhJnBs6mgXLzRQmR1RWY5s1QOk1JeAoOtqAuLC/h9CO3He4bCn2L4TWjUTg2GUKoDO6zx+vX/BOzuPyOlltyih4oYXiYiXdpPkSSdQo1BnmGCkSQXimtbHSx/uO0+weE9RUAAwnL+FmUuYK4J8bI2TPYnwe+p9cgYvdzvxJsTlzKcqpLeM8snL6VYsIwiVw96ih5uFecw+wrKX9NVZuv4ubY7jL/6+ZudZpqi7+X0AouOOcQdPwd6kzBEhJ4g9pseRGVqrtWvSos3gEOkVCaVfe2YSoEZR2k1YjyUVOqrtujDcKSbgroTbotDS6wbdLorPMh3zCvLUHJjHpA7tkT+V/nQKsBtTNzchHqrZVdHpFgy9XSzszQZUWVWcVZaoAOzE4qrjTrAXTc0ghs5PkTKUQnsAcBI4YUvFAoYCUysLK3BA49yYGFUPnoa9j3E89xoEdfWAX+P/mAIOIh73IDwR9r6fVncTVJ/D0M=
