language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
jobs:
  include:
  - stage: Test
    script:
    - echo "Testing"
    - docker build -t $DOCKER_USERNAME/express-boilerplate-test -f Dockerfile.test .
    - docker run --rm
  - stage: Build
    script:
    - echo "Building"
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "Docker login success"
    # - docker build -t $DOCKER_USERNAME/express-boilerplate .
    # - docker images
    # - docker tag $DOCKER_USERNAME/express-boilerplate $DOCKER_USERNAME/express-boilerplate
    # - docker push $DOCKER_USERNAME/express-boilerplate
  - stage: Publish
    script:
    - echo "Publishing"
env:
  global:
  - secure: QJMga6INpW0uY6KlKjgT2u8OK6kBdgRZWvvGn6559eib3a2gVWIDFZJvX8nyzLYRlgky1LWiSKyeZYhJzTxCcPSebxI9TUEpDrua9ciTR+1e1/yCVM/eu5nAqyRkWj9fBWOD27pXWQ5A0edJ6jowOWtPySarP7LPiH2Wy0C/8xkpIiR0wsynRAIZcIQ9RDPjnCY3A31Zx6LLXKBY+nE/c/vrIi/moOS8oHS4exZG//LeP24r/E6cYVY0fyfSD/zRYCARZXb9eFhqAYtajwWU/p1/SC4ssF1TMLI+hQrH5EgWAKhPQeUTOwQPEnsZyhKvytcDVCktAPkroVL+Og5QEG2yJ51FC8SC76t5qungiatEKXWjp/SMiwuWnKCSaW02fIqB8w18BKMLXNUQLgZ3rnT2QPPGD7DvK7oaJtmybnJAxwSgRaAJXpOlXdP7rwdXz1+mQxXHlDErNt5RjkKqbExpDE47NS8uv9fK9Wt78NJxFYlsz1kLCmMez9/eRMg6qgwNLa7w418Nog30Q7jqA/mWuw137jHQpGc5ZX5gLdSXVt2TZaWfEMwXJLrKXjNENi53QY/wphtQHfLARGz30xt3z8nBP0RNRLyivzLbdHTvXS9hYp0eAsRH9uAS84wWfEbcVZEhCte5GLQfOAk3b9iIP/Ox0K0x/11WU2SJicg=
  - secure: IpTiaX7sXnJE3E23gthH5HKW4uuXhw/mB4DljtvBta6S7UoCLU1iBgMEbXri77hKeRWIfvMkeK/85kjdjpMuq1SaThM6480LfXAegLeeZYiSBunESMshD/TxuRKbL19lBQgHkj3nfbkjmra5ai0BvMxzw6BunQmMao9a1PlxTAlhQh6vta7pgysbiN48j9PN5AQ9k9i3fbWIw0t17xPk5EyqdSru/Wip5S7I4EMNtiWj4oPFInwUXfyrjgU6SEZSMh1GAJAJWm/qjm+OrFeMqKRQtCByW/N9AMexWsMDW+37S9ueJwmKBilTAGWGEOvfehODjIREzwetmNTlQctcHYuAC7lUSocUUitfzM1s3rKo8m/9e+fA+6wHOwOR8PugD8W3zdoh1rjnBRmbQ+7jeEJ+ZflFJL6w69inT1FXBPOjwrFo7iRFmAriCN8Quci194IXhUoK34aEhT+9LpYY1syEC6G5g0g+IkUxyI+dpyyN0DZfxRxmqVvhspmvhLPNgBeoYWzX4DFWspsc5v5W9eXpMGz4xbcltM3pa0vkzBI+cjbkixk0+Ugc3i+hvI8EZFjiVdnyai4Vhxij3zFIVf4ZCvp3DTPSOSbMWAZci/k7S+vGbkWOW6qcQPxt8yMj2RVHOtqb9uAy40cNhE0wExKH21SdQx55X4nWaYv4PPw=
