FROM node:12-alpine

ARG LAST_COMMIT_SHA
ENV LAST_COMMIT_SHA $LAST_COMMIT_SHA

# Create application directory
WORKDIR './app'

# Bundle app
COPY . .

# Install depedencies
RUN npm install

EXPOSE 3000

CMD ["npm", "run", "test"]